# Generated by Django 4.1.1 on 2022-09-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Номер заказа')),
                ('price_dol', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена в $')),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена в Руб.')),
                ('shipment_date', models.DateField(verbose_name='Дата поставки')),
            ],
            options={
                'verbose_name': 'Данные листа',
                'verbose_name_plural': 'Данные листа',
                'ordering': ['-pk'],
            },
        ),
    ]
