# Generated by Django 4.1.1 on 2022-09-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sheetdata_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetdata',
            options={'ordering': ['number'], 'verbose_name': 'Данные листа', 'verbose_name_plural': 'Данные листа'},
        ),
        migrations.AlterField(
            model_name='sheetdata',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Номер'),
        ),
    ]
