# Generated by Django 4.1.1 on 2022-09-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_sheetdata_options_alter_sheetdata_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetdata',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер'),
        ),
    ]
