version: '3.8'

services:
  db:
    image: postgres:10-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432

  redis:
    image: redis:alpine

  web:
    build:
        context: ./sheets_proj
        dockerfile: Dockerfile
    command: bash -c "
        python manage.py makemigrations
        && python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./sheets_proj/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  celery:
    restart: always
    build:
      context: ./sheets_proj
      dockerfile: Dockerfile
    command: celery -A sheets_proj worker -l info
    volumes:
      - ./sheets_proj/:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build:
      context: ./sheets_proj
      dockerfile: Dockerfile
    command: celery -A sheets_proj beat -l info
    volumes:
      - ./sheets_proj/:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web
